# Generated by Django 6.0.3 on 2026-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='periodo',
            field=models.CharField(blank=True, choices=[('P1', 'Primer Periodo'), ('P2', 'Segundo Periodo'), ('P3', 'Tercer Periodo'), ('P4', 'Cuarto Periodo')], max_length=20, null=True, verbose_name='Periodo académico'),
        ),
    ]
