# Generated by Django 4.2.16 on 2026-03-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='destacada',
            field=models.BooleanField(default=False, help_text='Aparece fija al inicio del blog.'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='resumen',
            field=models.TextField(blank=True, help_text='Breve descripción visible en el listado.', max_length=500),
        ),
    ]
