# Generated by Django 4.2.16 on 2026-03-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_estudiante',
            field=models.CharField(blank=True, help_text='Código único para estudiantes', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_hijo',
            field=models.CharField(blank=True, help_text='Código del hijo para acudientes', max_length=20),
        ),
    ]
