# Generated by Django 4.2.16 on 2026-03-06 18:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(choices=[(1, 'Primer Período'), (2, 'Segundo Período'), (3, 'Tercer Período'), (4, 'Cuarto Período')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Parcial 1, Taller 2', max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(help_text='Relaciona al profesor, materia y curso al mismo tiempo.', on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='academico.asignacionprofesormateria')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-fecha'],
            },
        ),
    ]
