# Generated by Django 4.2.16 on 2026-03-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_entrega', models.DateTimeField()),
                ('valor_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.CreateModel(
            name='EntregaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('comentario', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('retroalimentacion', models.TextField(blank=True)),
                ('entregado_en', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.actividad')),
            ],
            options={
                'verbose_name': 'Entrega de Actividad',
                'verbose_name_plural': 'Entregas de Actividades',
            },
        ),
    ]
