# Generated by Django 4.2.16 on 2026-03-06 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academico', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaactividad',
            name='estudiante',
            field=models.ForeignKey(limit_choices_to={'rol': 'ESTUDIANTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actividad',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='academico.asignacionprofesormateria'),
        ),
        migrations.AlterUniqueTogether(
            name='entregaactividad',
            unique_together={('actividad', 'estudiante')},
        ),
    ]
