# Generated by Django 6.0.3 on 2026-03-06 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comercial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='acudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_comercial', to=settings.AUTH_USER_MODEL, verbose_name='Acudiente'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comercial.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AddField(
            model_name='detallecotizacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='productos',
            field=models.ManyToManyField(through='comercial.DetalleCotizacion', to='comercial.producto', verbose_name='Productos'),
        ),
    ]
